config/routes.rb
Rails.application.routes.draw do
  # Errors
  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_server_error"
  # Devise
  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }
  devise_scope(:user) { get "logout", to: "devise/sessions#destroy" }
  # Attachments
  resources :attachments do
    member do
      get :download, to: "attachments#download"
      get :history, to: "attachments#history"
    end
  end
  # Educations
  resources :educations
  # Education courses
  resources :education_courses do
    member do
      get :history, to: "education_courses#history"
    end
  end
  # Education degrees
  resources :education_degrees do
    member do
      get :history, to: "education_degrees#history"
    end
  end
  # Events
  resources :events do
    member do
      get   :description,        to: "events#description"
      get   :"description/edit", to: "events#edit_description"
      put   :description,        to: "events#update_description"
      patch :description,        to: "events#update_description"
      get   :history,            to: "events#history"
    end
  end
  resources :event_participants
  # Event Roles
  resources :event_roles do
    member do
      get :history, to: "event_roles#history"
    end
  end
  # Pictures
  resources :pictures
  # Imports
  namespace :imports, only: [:index, :show] do
    resources :memberships, only: [:create, :index, :show] do
      member do
        get :download, to: "memberships#download"
      end
    end
    resources :organizations, only: [:create, :index, :show] do
      member do
        get :download, to: "organizations#download"
      end
    end
  end
  # Links
  resources :links do
    member do
      get :download, to: "links#download"
      get :history, to: "links#history"
    end
  end
  # Locations
  resources :locations, only: [:show] do
    collection do
      post :reverse_geocode, to: "locations#reverse_geocode"
    end
  end
  # Names
  resources :names, except: [:show]
  # Notes
  resources :notes, except: [:edit, :update]
  # Organizations
  resources :organizations do
    member do
      get   :description,        to: "organizations#description"
      get   :"description/edit", to: "organizations#edit_description"
      put   :description,        to: "organizations#update_description"
      patch :description,        to: "organizations#update_description"
      get   :history,            to: "organizations#history"
    end
  end
  # Organization departments
  resources :organization_departments
  # Organiation members
  resources :organization_members
  # Organization owners
  resources :organization_owners
  # Organization positions
  resources :organization_positions do
    member do
      get :history, to: "organization_positions#history"
    end
  end
  # People
  resources :people do
    member do
      get   :biography,        to: "people#biography"
      get   :"biography/edit", to: "people#edit_biography"
      put   :biography,        to: "people#update_biography"
      patch :biography,        to: "people#update_biography"
      get   :history,          to: "people#history"
    end
  end
  # Preferences
  resource :preferences, only: [:edit, :update]
  # Relationships
  resources :relationships
  # Tags
  resources :tags do
    member do
      get :history, to: "tags#history"
    end
  end
  get "/event_tags/:id", to: redirect("/tags/%{id}"), as: "event_tag"
  get "/organization_tags/:id", to: redirect("/tags/%{id}"), as: "organization_tag"
  get "/person_tags/:id", to: redirect("/tags/%{id}"), as: "person_tag"
  # User Groups
  resources :user_groups, only: [:index, :show] do
    member do
      post "users", to: "user_groups#add_user", as: :add_user
      delete "users/:user_id", to: "user_groups#remove_user", as: :remove_user
    end
  end
  # Root
  root to: "home#index"
end

app/models/import.rb
class Import < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_file

  default_value :status, "pending"
  default_value :logs, []

  belongs_to :user

  validates_presence_of  :user
  validates_inclusion_of :status, in: %w(pending processing success error)

  validate :validate_ods_file
  validate :validate_headers

  def display_name
    "#{self.class.model_name.human} - #{I18n.l(created_at, format: :long)}"
  end

  def finished?
    %w(success error).include?(status)
  end

  def log_info(message, line_number)
    return if message.nil?
    new_log = { severity: "info", line_number: line_number, message: message }
    update_attributes!(logs: logs + [new_log])
  end

  def log_error(message, line_number = nil)
    return if message.nil?
    new_log = { severity: "error", line_number: line_number, message: message }
    update_attributes!(logs: logs + [new_log])
  end

  def each_line_with_number
    (2..sheet.count).each do |line_number|
      current_row = sheet.row(line_number)
      line = columns.each_with_index
                    .each_with_object({}) do |(column, index), hash|
        value = current_row[index]
        value.strip! if value.is_a?(String)
        if hash.key?(column)
          hash[column] = [hash[column]] unless hash[column].is_a?(Array)
          hash[column] << value
        else
          hash[column] = value
        end
      end
      yield(line, line_number)
    end
  end

  private

  def validate_ods_file
    return unless ods.nil?
    errors.add(:file, I18n.t("errors.invalid_format"))
  end

  def validate_headers
    return if ods.nil?
    missing_columns = mandatory_columns - columns
    return if missing_columns.empty?
    errors.add(:file, I18n.t(
      "errors.import.missing_columns",
      missing_columns: missing_columns.join(", ")
    ))
  end

  def columns
    @columns ||= begin
      sheet.row(1)
           .select(&:present?)
           .map(&:downcase)
           .map(&:to_sym)
    end
  end

  def sheet
    ods.sheet(0)
  end

  def ods
    return nil unless file_extension == ".ods"
    decrypted = file_decrypted
    @ods ||= Roo::OpenOffice.new(decrypted.path) rescue nil
  end

  def mandatory_columns
    raise NotImplementedError
  end
end

app/controllers/imports/memberships_controller.rb
class Imports::MembershipsController < Imports::ResourcesController
  private

  def resources_class
    MembershipsImport
  end

  def import_job_class
    ImportMembershipsJob
  end
end

app/controllers/imports/organizations_controller.rb
class Imports::OrganizationsController < Imports::ResourcesController
  private

  def resources_class
    OrganizationsImport
  end

  def import_job_class
    ImportOrganizationsJob
  end
end

app/controllers/imports/resources_controller.rb
class Imports::ResourcesController < ResourcesController
  # POST /imports/[collection]
  def create
    @resource = resources_class.new(create_params)
    authorize! :create, @resource
    if @resource.save
      flash[:success] = Import.human_attribute_name(:created)
      redirect_to url_for(controller: controller_name,
                          action: "show",
                          id: @resource.id,
                          only_path: true)
      import_job_class.perform_later(@resource.id)
    else
      flash[:error] = @resource.errors.first[1]
      redirect_to url_for(controller: controller_name, action: "index")
    end
  end

  # GET /imports/[collection]/:id/download
  def download
    @resource = resources_class.find(params.require(:id))
    authorize! :read, @resource
    send_file(@resource.file_decrypted.path,
              filename: "#{@resource.display_name.gsub(/\W/, "_")}#{@resource.file_extension}")
  end

  private

  def import_job_class
    raise NotImplementedError
  end

  def create_params
    uploaded_file = params.require(:import)[:file_unencrypted]
    file_extension = uploaded_file.present? ? File.extname(uploaded_file.path) : nil
    params.require(:import)
          .permit(:file_unencrypted)
          .merge(user_id: current_user.id,
                 file_extension: file_extension)
  end
end

app/views/imports/memberships/_import_details_pt-BR.html.erb
<div class="modal fade" id="import-details-modal" tabindex="-1"
     role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header py-1">
        <h5 class="modal-title" id="deleteModalTitle">
          Descrição das colunas
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag image_path("open-iconic/x.svg") %>
        </button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_FIRST_NAME</strong>
          O nome da pessoa
          <br/>
          <div class="small">a pessoa será criada se não existir no banco de dados</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_LAST_NAME</strong>
          O sobrenome da pessoa
          <br/>
          <div class="small">a pessoa será criada se não existir no banco de dados</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_DATE_OF_BIRTH (opcional)</strong>
          Data de nascimento da pessoa
          <br/>
          <div class="small">as células devem estar formatadas como data no documento</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_DATE_OF_DEATH (opcional)</strong>
          Data de falecimento da pessoa
          <br/>
          <div class="small">as células devem estar formatadas como data no documento</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_APPROXIMATE_DATES (opcional)</strong>
          Se a célula não estiver em branco, significa que as datas de nascimento e falecimento da pessoa são aproximadas
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">PERSON_TAG (opcional / é permitido haver mais de uma por linha)</strong>
          Etiqueta que será atribuída à pessoa
          <br/>
          <div class="small">deve existir no banco de dados</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">ORGANIZATION_NAME</strong>
          O nome da organização
          <br/>
          <div class="small">deve existir no banco de dados</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_POSITION (opcional)</strong>
          Cargo no qual a pessoa está filiada à organização
          <br/>
          <div class="small">deve existir no banco de dados</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_FROM_DATE (opcional)</strong>
          Data de início da filiação
          <br/>
          <div class="small">as células devem estar formatadas como data no documento</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_TO_DATE (opcional)</strong>
          Data de fim da filiação
          <br/>
          <div class="small">as células devem estar formatadas como data no documento</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_APPROXIMATE_DATES (opcional)</strong>
          Se a célula não estiver em branco, significa que as datas de início e fim da filiação são aproximadas
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_LOCATION_HEADQUARTERS (opcional)</strong>
          Se a célula não estiver em branco, significa que a localização da filiação é a sede da organização
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_SOURCE_URL (opcional)</strong>
          URL da fonte da informação
          <br/>
          <div class="small">deve começar com http:// ou https://</div>
        </div>
        <div class="mb-3">
          <strong class="pb-1 d-block">MEMBERSHIP_SOURCE_LABEL (opcional)</strong>
          Título da fonte da informação
        </div>
      </div>
    </div>
  </div>
</div>

app/views/imports/memberships/index.html.erb
<% title Import.model_name.human(count: 2) %>

<div id="index-imports" class="index imports">
  <%= render partial: "import_details_#{I18n.locale}" %>
  <div class="p-3 my-3 bg-white border-gray border rounded">
    <h5 class="pb-2">
      <%= t("observatorio.import.title") %>
      <span class="small">(<%= link_to t("observatorio.import.download_template"), asset_path("import_memberships_template.ods") %>)</span>
      <a href="#import-details-modal" class="has-tooltip rounded-circle btn btn-outline-info d-inline-block line-height-1 p-1 ml-1"
                  data-placement="top" data-toggle="modal" title="<%= Import.human_attribute_name(:see_details) %>" >
        <%= info class: "svg svg-info pict-info d-inline-block", width: "12.8px", height: "12.8px" %>
      </a>
    </h5>
    <%= form_tag(imports_memberships_path, method: :post, multipart: true) do %>
      <%= file_field_tag "import[file_unencrypted]", class: "form-control form-control-sm", required: true %>
      <div class="text-right mt-3">
        <%= submit_tag t("observatorio.import.submit"), class: "btn btn-primary btn-sm" %>
      </div>
    <% end %>
  </div>

  <div class="p-3 p-md-3 my-3 bg-white border-gray border rounded">
    <% @resources.each do |import| %>
      <div class="media search-result mb-2">
        <% if can? :read, import %>
          <a href='<%= imports_membership_path(import.id) %>'>
        <% end %>
        <% case import.status %>
        <% when "pending" %>
          <div class="btn btn-outline-secondary thumb rounded-circle has-tooltip" style="padding-top: 12px"
               data-placement="top" title='<%= t("observatorio.status.#{import.status}") %>'>
            <%= ellipses class: "svg svg-secondary", width: "15px", height: "15px" %>
          </div>
        <% when "processing" %>
          <div class="btn btn-outline-info thumb rounded-circle has-tooltip" style="padding-top: 12px"
               data-placement="top" title='<%= t("observatorio.status.#{import.status}") %>'>
            <%= ellipses class: "svg svg-info", width: "15px", height: "15px" %>
          </div>
        <% when "success" %>
          <div class="btn btn-outline-success thumb rounded-circle has-tooltip" style="padding-top: 12px"
               data-placement="top" title='<%= t("observatorio.status.#{import.status}") %>'>
            <%= check class: "svg svg-success", width: "15px", height: "15px" %>
          </div>
        <% when "error" %>
          <div class="btn btn-outline-danger thumb rounded-circle has-tooltip" style="padding-top: 12px"
               data-placement="top" title='<%= t("observatorio.status.#{import.status}") %>'>
            <%= x class: "svg svg-danger", width: "15px", height: "15px" %>
          </div>
        <% end %>
        <p class="media-body ml-md-3 mb-0 pb-2 pb-md-0">
          <strong>
            <% if can? :read, import %>
              <%= link_to display_name(import), imports_membership_path(import.id) %>
            <% else %>
              <%= display_name(import) %>
            <% end %>
          </strong>
        </p>
      </div>
    <% end %>
    <nav class="mt-3">
      <ul class="pagination pagination-sm mb-0">
        <li class="page-item ml-auto <%= "disabled" if @page == 1 %>">
          <a class="page-link" href="<%= @page == 1 ? "#" : imports_path(query: @query, page: @page - 1) %>">
            <%= Import.human_attribute_name(:previous_page) %>
          </a>
        </li>
        <li class="page-item <%= "disabled" if @last_page %>">
          <a class="page-link" href="<%= @last_page ? "#" : imports_path(query: @query, page: @page + 1) %>">
            <%= Import.human_attribute_name(:next_page) %>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/imports/memberships/show.html.erb
<% title display_name(@resource) %>

<div id="show-imports" class="show imports">
  <!-- General information -->
  <div class="p-3 my-3 bg-white text-center border-gray border rounded general-infos">
    <div class="text-right p-2 d-none d-md-block">
      <a href="<%= download_imports_membership_path(@resource) %>" class="action has-tooltip mx-1"
         data-placement="top" title="<%= Import.human_attribute_name(:download) %>">
        <%= download class: "svg svg-primary", width: "24px", height: "24px" %>
      </a>
    </div>
    <h2><%= display_name(@resource) %></h2>
    <h5 class="d-inline-block">
      <% case @resource.status %>
      <% when "pending" %>
        <span class='badge badge-pill badge-secondary status-badge <%= "status-finished" if @resource.finished? %>'>
          <%= t("observatorio.status.#{@resource.status}") %>
        </span>
      <% when "processing" %>
        <span class='badge badge-pill badge-info status-badge <%= "status-finished" if @resource.finished? %>'>
          <%= t("observatorio.status.#{@resource.status}") %>
        </span>
      <% when "success" %>
        <span class='badge badge-pill badge-success status-badge <%= "status-finished" if @resource.finished? %>'>
          <%= t("observatorio.status.#{@resource.status}") %>
        </span>
      <% when "error" %>
        <span class='badge badge-pill badge-danger status-badge <%= "status-finished" if @resource.finished? %>'>
          <%= t("observatorio.status.#{@resource.status}") %>
        </span>
      <% end %>
    </h5>
  </div>

  <div class="p-3 my-2 bg-black border-gray border rounded import-logs">
    <% if @resource.finished? %>
      <% @resource.logs.each_with_index do |log, index| %>
        <% case log["severity"] %>
        <% when "info" %>
          <samp class='<%= index.even? ? "text-white" : "text-info" %> small'>
        <% when "error" %>
          <samp class="text-danger small">
        <% end %>
          <% if log["line_number"].present? %>
            <strong><%= t("observatorio.import.logs.line_number_prefix") %> <%= log["line_number"] %> - </strong>
          <% end %>
          <%= log["message"] %>
        </samp>
        </br>
      <% end %>
    <% else %>
      <samp class="loading small mx-auto">
        <%= circle class: "svg-secondary" %>
        <%= circle class: "svg-secondary" %>
        <%= circle class: "svg-secondary" %>
      </samp>
    <% end %>
  </div>
</div>