config/routes.rb
Rails.application.routes.draw do
  # Errors
  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_server_error"
  # Devise
  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }
  devise_scope(:user) { get "logout", to: "devise/sessions#destroy" }
  # Attachments
  resources :attachments do
    member do
      get :download, to: "attachments#download"
      get :history, to: "attachments#history"
    end
  end
  # Educations
  resources :educations
  # Education courses
  resources :education_courses do
    member do
      get :history, to: "education_courses#history"
    end
  end
  # Education degrees
  resources :education_degrees do
    member do
      get :history, to: "education_degrees#history"
    end
  end
  # Events
  resources :events do
    member do
      get   :description,        to: "events#description"
      get   :"description/edit", to: "events#edit_description"
      put   :description,        to: "events#update_description"
      patch :description,        to: "events#update_description"
      get   :history,            to: "events#history"
    end
  end
  resources :event_participants
  # Event Roles
  resources :event_roles do
    member do
      get :history, to: "event_roles#history"
    end
  end
  # Pictures
  resources :pictures
  # Imports
  namespace :imports, only: [:index, :show] do
    resources :memberships, only: [:create, :index, :show] do
      member do
        get :download, to: "memberships#download"
      end
    end
    resources :organizations, only: [:create, :index, :show] do
      member do
        get :download, to: "organizations#download"
      end
    end
  end
  # Links
  resources :links do
    member do
      get :download, to: "links#download"
      get :history, to: "links#history"
    end
  end
  # Locations
  resources :locations, only: [:show] do
    collection do
      post :reverse_geocode, to: "locations#reverse_geocode"
    end
  end
  # Names
  resources :names, except: [:show]
  # Notes
  resources :notes, except: [:edit, :update]
  # Organizations
  resources :organizations do
    member do
      get   :description,        to: "organizations#description"
      get   :"description/edit", to: "organizations#edit_description"
      put   :description,        to: "organizations#update_description"
      patch :description,        to: "organizations#update_description"
      get   :history,            to: "organizations#history"
    end
  end
  # Organization departments
  resources :organization_departments
  # Organiation members
  resources :organization_members
  # Organization owners
  resources :organization_owners
  # Organization positions
  resources :organization_positions do
    member do
      get :history, to: "organization_positions#history"
    end
  end
  # People
  resources :people do
    member do
      get   :biography,        to: "people#biography"
      get   :"biography/edit", to: "people#edit_biography"
      put   :biography,        to: "people#update_biography"
      patch :biography,        to: "people#update_biography"
      get   :history,          to: "people#history"
    end
  end
  # Preferences
  resource :preferences, only: [:edit, :update]
  # Relationships
  resources :relationships
  # Tags
  resources :tags do
    member do
      get :history, to: "tags#history"
    end
  end
  get "/event_tags/:id", to: redirect("/tags/%{id}"), as: "event_tag"
  get "/organization_tags/:id", to: redirect("/tags/%{id}"), as: "organization_tag"
  get "/person_tags/:id", to: redirect("/tags/%{id}"), as: "person_tag"
  # User Groups
  resources :user_groups, only: [:index, :show] do
    member do
      post "users", to: "user_groups#add_user", as: :add_user
      delete "users/:user_id", to: "user_groups#remove_user", as: :remove_user
    end
  end
  # Root
  root to: "home#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_name_and_display_priority
  has_paper_trail
  has_immutable_attributes :type

  validate :valid_type

  private

  def valid_type
    return if Tag.subclasses.map(&:name).include?(type.to_s)
    errors.add(:type, I18n.t("errors.messages.inclusion"))
  end
end

app/controllers/tags_controller.rb
class TagsController < ResourcesController
  def authorize!(action, resource)
    if resource == Tag
      subtype = params.require(:tag).require(:type).constantize
      authorize! action, subtype
    else
      super
    end
  end

  private

  def resources_class
    Tag
  end

  def index_params
    index_or_new_params
  end

  def new_params
    index_or_new_params
  end

  def index_or_new_params
    params.require(:tag)
          .permit(:type)
  end

  def create_params
    params.require(:tag)
          .permit(:type, :name)
  end

  def update_params
    params.require(:tag)
          .permit(:name)
  end

  def versions_unsorted
    resource_versions
  end
end

app/views/tags/_history_entry.html.erb
<% item = version.item_state %>
<% item_klass = version.item_klass %>
<div class="media item">
  <div class="media-body mb-0 mt-0 mb-2">
    <div class="d-inline-block main">
      <strong class="mb-md-0">
        <%= display_time(version.created_at) %>
      </strong>
      &middot;
      <%= display_user(version.user) %>
    </div>
    <span class="ml-2 d-block">
      <%= t("paper_trail.tag.#{version.event}").html_safe %>
      <a class="btn btn-info small btn-sm py-0 px-1 ml-1"
         data-toggle="collapse"
         href="#details<%= version.id %>"
         role="button"
         aria-expanded="false"
         aria-controls="details">
         <%= t("paper_trail.details") %>
      </a>
    </span>
    <div class="collapse small" id="details<%= version.id %>">
      <ul class="mt-1 mb-0 pl-4" style="list-style-type: none">
        <% if version.converted_changeset.key?("name") %>
          <li>
            <strong><%= Tag.human_attribute_name(:name) %>:</strong>
            <%= Differ.diff_by_word(
                  *version.converted_changeset["name"].reverse
                ).format_as(:html).html_safe %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tags/create.html.erb
<div class="modal-body">
  <%= t("observatorio.models.tag.created",
        tag: tag.strong(display_name(@resource))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

app/views/tags/destroy.html.erb
<div class="modal-body">
  <%= t("observatorio.models.tag.destroyed",
        tag: tag.strong(display_name(@resource))).html_safe %>
</div>
<div class="modal-footer">
  <%= link_to t("observatorio.dialog.ok"), tags_path(tag: { type: @resource.type }),
        class: "btn btn-primary btn-sm"%>
</div>

app/views/tags/form.html.erb
<%= form_for @resource, url: @resource.new_record? ? tags_path : tag_path(@resource) do |f| %>
  <%= hidden_field_tag "tag[type]", @resource.type %>
  <div class="modal-body">
    <div class="form-group row">
      <% name_error = @resource.errors[:name]&.first  %>
      <%= label_tag "tag[name]", @resource.class.human_attribute_name(:name), class: "col-3" %>
      <%= text_field_tag "tag[name]", @resource.name,
            :"data-autofocus" => true, required: true, autocomplete: "off",
            class: "form-control form-control-sm col-8 #{"is-invalid" if name_error }" %>
      <% if name_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-8 offset-3">
              <%= name_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <%= submit_tag t("observatorio.save"), class: "btn btn-primary btn-sm" %>
    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">
      <%= t("observatorio.cancel") %>
    </button>
  </div>
<% end %>

app/views/tags/index.html.erb
<% subtype = params.require(:tag).require(:type).constantize %>

<% title subtype.model_name.human(count: 2) %>

<div id="index-tags" class="index tags">
  <div class="p-3 my-3 bg-white border-gray border rounded">
    <h5 class="pb-2">
      <%= t("observatorio.search.title") %>
    </h5>
    <%= form_tag({ controller: "tags", action: "index" }, method: :get) do %>
      <%= hidden_field_tag "tag[type]", subtype %>
      <%= text_field_tag :search, @search, class: "form-control form-control-sm" %>
      <div class="text-right mt-3">
        <%= submit_tag t("observatorio.search.submit"), class: "btn btn-primary btn-sm" %>
        <%= link_to t("observatorio.search.clean_filters"), tags_path,
              class: "btn btn-secondary btn-sm" %>
      </div>
    <% end %>
  </div>

  <div class="p-3 p-md-3 my-3 bg-white border-gray border rounded">
    <% @resources.each do |tag| %>
      <div class="media search-result mb-2">
        <p class="media-body mb-0 pb-2 pb-md-0">
          <strong>
            <%= link_to display_name(tag), tag_url(tag) %>
          </strong>
        </p>
      </div>
    <% end %>
    <nav class="mt-3">
      <ul class="pagination pagination-sm mb-0">
        <li class="page-item ml-auto <%= "disabled" if @page == 1 %>">
          <a class="page-link"
            href="<%= @page == 1 ?
                        "#" : tags_path(
                                search: @search,
                                page: @page - 1,
                                tag: { type: subtype }
                              ) %>">
            <%= subtype.human_attribute_name(:previous_page) %>
          </a>
        </li>
        <li class="page-item <%= "disabled" if @last_page %>">
          <a class="page-link"
              href="<%= @last_page ?
                          "#" : tags_path(
                                  search: @search,
                                  page: @page + 1,
                                  tag: { type: subtype }
                                ) %>">
            <%= subtype.human_attribute_name(:next_page) %>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/tags/show.html.erb
<% title display_name(@resource) %>

<div id="show-person-tags" class="show person-tags">
  <%=
    render partial: "modal_form", locals: {
      url: edit_tag_path(@resource),
      modal_id: "edit-tag-#{@resource.id}",
      modal_title: @resource.class.human_attribute_name(:edit)
    }
  %>
  <%=
    render partial: "confirm_delete", locals: {
      record: @resource,
      confirm_message: @resource.class.human_attribute_name(
        :destroy_confirm, record: tag.strong(display_name(@resource))
      ).html_safe,
      url: tag_path(@resource),
      modal_id: "destroy-tag-#{@resource.id}",
      modal_title: @resource.class.human_attribute_name(:destroy)
    }
  %>
  <div class="p-3 my-3 bg-white text-center border-gray border rounded general-infos">
    <div class="text-right p-2 d-none d-md-block">
      <% if can? :update, @resource %>
        <a href='#edit-tag-<%= @resource.id %>' class='action has-tooltip mx-3' data-toggle="modal"
           data-placement="top" title="<%= @resource.class.human_attribute_name(:edit) %>">
          <%= pencil class: "svg svg-primary", width: "24px", height: "24px" %>
        </a>
      <% end %>
      <% if can? :delete, @resource %>
        <a href="#destroy-tag-<%= @resource.id %>" class="action has-tooltip mx-1" data-toggle="modal"
           data-placement="top" title="<%= @resource.class.human_attribute_name(:destroy) %>">
          <%= x class: "svg svg-danger", width: "24px", height: "24px" %>
        </a>
      <% end %>
    </div>
    <h2 class="mb-3">
      <span class="badge badge-pill badge-info">
        <%= display_name(@resource) %>
      </span>
    </h2>
    <div class="small text-muted">
      <%= @resource.class.human_attribute_name(:created_at) %>:
      <%= display_time(@resource.created_at) %>
    </div>
    <div class="small text-muted">
      <%= @resource.class.human_attribute_name(:updated_at) %>:
      <%= display_time(@resource.updated_at) %>
    </div>
  </div>

  <!-- History -->
  <%=
    render partial: "subsection", locals: {
      subsection_title: @resource.class.human_attribute_name(:history),
      subsection_id: "history-subsection",
      subsection_class: "history",
      resource: @resource,
      refresh_element_url: history_tag_path(@resource)
    }
  %>
</div>

app/views/tags/update.html.erb
<div class="modal-body">
  <%= t("observatorio.models.tag.updated").html_safe %>
</div>
<div class="modal-footer">
  <%= link_to t("observatorio.dialog.ok"), tag_path(@resource),
        class: "btn btn-primary btn-sm"%>
</div>