config/routes.rb
Rails.application.routes.draw do
  # Errors
  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_server_error"
  # Devise
  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }
  devise_scope(:user) { get "logout", to: "devise/sessions#destroy" }
  # Attachments
  resources :attachments do
    member do
      get :download, to: "attachments#download"
      get :history, to: "attachments#history"
    end
  end
  # Educations
  resources :educations
  # Education courses
  resources :education_courses do
    member do
      get :history, to: "education_courses#history"
    end
  end
  # Education degrees
  resources :education_degrees do
    member do
      get :history, to: "education_degrees#history"
    end
  end
  # Events
  resources :events do
    member do
      get   :description,        to: "events#description"
      get   :"description/edit", to: "events#edit_description"
      put   :description,        to: "events#update_description"
      patch :description,        to: "events#update_description"
      get   :history,            to: "events#history"
    end
  end
  resources :event_participants
  # Event Roles
  resources :event_roles do
    member do
      get :history, to: "event_roles#history"
    end
  end
  # Pictures
  resources :pictures
  # Imports
  namespace :imports, only: [:index, :show] do
    resources :memberships, only: [:create, :index, :show] do
      member do
        get :download, to: "memberships#download"
      end
    end
    resources :organizations, only: [:create, :index, :show] do
      member do
        get :download, to: "organizations#download"
      end
    end
  end
  # Links
  resources :links do
    member do
      get :download, to: "links#download"
      get :history, to: "links#history"
    end
  end
  # Locations
  resources :locations, only: [:show] do
    collection do
      post :reverse_geocode, to: "locations#reverse_geocode"
    end
  end
  # Names
  resources :names, except: [:show]
  # Notes
  resources :notes, except: [:edit, :update]
  # Organizations
  resources :organizations do
    member do
      get   :description,        to: "organizations#description"
      get   :"description/edit", to: "organizations#edit_description"
      put   :description,        to: "organizations#update_description"
      patch :description,        to: "organizations#update_description"
      get   :history,            to: "organizations#history"
    end
  end
  # Organization departments
  resources :organization_departments
  # Organiation members
  resources :organization_members
  # Organization owners
  resources :organization_owners
  # Organization positions
  resources :organization_positions do
    member do
      get :history, to: "organization_positions#history"
    end
  end
  # People
  resources :people do
    member do
      get   :biography,        to: "people#biography"
      get   :"biography/edit", to: "people#edit_biography"
      put   :biography,        to: "people#update_biography"
      patch :biography,        to: "people#update_biography"
      get   :history,          to: "people#history"
    end
  end
  # Preferences
  resource :preferences, only: [:edit, :update]
  # Relationships
  resources :relationships
  # Tags
  resources :tags do
    member do
      get :history, to: "tags#history"
    end
  end
  get "/event_tags/:id", to: redirect("/tags/%{id}"), as: "event_tag"
  get "/organization_tags/:id", to: redirect("/tags/%{id}"), as: "organization_tag"
  get "/person_tags/:id", to: redirect("/tags/%{id}"), as: "person_tag"
  # User Groups
  resources :user_groups, only: [:index, :show] do
    member do
      post "users", to: "user_groups#add_user", as: :add_user
      delete "users/:user_id", to: "user_groups#remove_user", as: :remove_user
    end
  end
  # Root
  root to: "home#index"
end

app/models/education.rb
class Education < ApplicationRecord
  has_paper_trail
  has_links             :sources
  has_attachments
  has_date_boundaries
  has_immutable_attributes :school_id, :student_id

  belongs_to :student, class_name: "Person"
  belongs_to :school,  class_name: "Organization"
  belongs_to :course,  class_name: "EducationCourse"
  belongs_to :degree,  class_name: "EducationDegree"

  validates_presence_of :student
  validates_presence_of :school
  validate              :assert_organization_is_school

  private

  def assert_organization_is_school
    return if school.nil? || school.school?
    errors.add(:school_id, errors.generate_message(:school, :should_be_school))
  end
end

app/controllers/educations_controller.rb
class EducationsController < ResourcesController
  layout false

  # GET /educations
  def index
    super
    @resources = @resources
                  .includes(:student,
                            :school,
                            :course,
                            :degree,
                            :sources,
                            :attachments)
                  .order(:from_date, :to_date)
  end

  private

  def authorize!(action, resource)
    if action == :list && resource == Education
      student_id = params.require(:education)[:student_id]
      if student_id.present?
        student = Person.find(student_id)
        authorize! :read, student
      else
        school_id = params.require(:education).require(:school_id)
        school = Organization.find(school_id)
        authorize! :read, school
      end
    else
      super
    end
  end

  def resources_per_page
    nil
  end

  def resources_class
    Education
  end

  def index_params
    index_or_new_params
  end

  def new_params
    index_or_new_params
  end

  def index_or_new_params
    params.require(:education)
          .permit(:school_id,
                  :student_id)
  end

  def create_params
    params.require(:education)
          .permit(:school_id,
                  :student_id,
                  :course_id,
                  :degree_id,
                  :from_date,
                  :to_date,
                  :approximate_dates)
  end

  def update_params
    params.require(:education)
          .permit(:course_id,
                  :degree_id,
                  :from_date,
                  :to_date,
                  :approximate_dates)
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
  def schools_options
    @_schools_options ||= begin
      Organization.school.map { |school| [display_name(school), school.id] }
    end
  end

  def degrees_options
    @_degrees_options ||= begin
      EducationDegree.all.map { |c| [display_name(c), c.id] }
    end
  end

  def courses_options
    @_courses_options ||= begin
      EducationCourse.all.map { |c| [display_name(c), c.id] }
    end
  end
end

app/views/educations/_history_entry.html.erb
<% item = version.item_state(belongs_to: true) %>
<% student = item.student %>
<% school = item.school %>
<% event = version.event %>
<div class="media item">
  <div class="media-body mb-0 mt-0 mb-2">
    <div class="d-inline-block main">
      <strong class="mb-md-0">
        <%= display_time(version.created_at) %>
      </strong>
      &middot;
      <%= display_user(version.user) %>
    </div>
    <span class="ml-2 d-block">
      <span class="school-only">
        <%= t("paper_trail.education.school.#{event}",
              student: tag.strong(display_resource(student))).html_safe %>
      </span>
      <span class="student-only">
        <%= t("paper_trail.education.student.#{event}",
              school: tag.strong(display_resource(school))).html_safe %>
      </span>
      <% if event != "destroy" %>
        <a class="btn btn-info small btn-sm py-0 px-1 ml-1"
           data-toggle="collapse"
           href="#details<%= version.id %>"
           role="button"
           aria-expanded="false"
           aria-controls="details">
          <%= t("paper_trail.details") %>
        </a>
      <% end %>
    </span>
    <% if event != "destroy" %>
      <div class="collapse small" id="details<%= version.id %>">
        <ul class="mt-1 mb-0 pl-4" style="list-style-type: none">
          <% if version.converted_changeset.key?("course_id") %>
            <li>
              <strong><%= Education.human_attribute_name(:course) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["course_id"].reverse.map { |c| display_resource(c) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("degree_id") %>
            <li>
              <strong><%= Education.human_attribute_name(:degree) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["degree_id"].reverse.map { |d| display_resource(d) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("from_date") %>
            <li>
              <strong><%= Education.human_attribute_name(:from_date) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["from_date"].reverse.map { |d| display_time(d) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("to_date") %>
            <li>
              <strong><%= Education.human_attribute_name(:to_date) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["to_date"].reverse.map { |d| display_time(d) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("approximate_dates") %>
            <li>
              <strong><%= Education.human_attribute_name(:approximate_dates) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["approximate_dates"].reverse.map { |b| display_boolean(b) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/educations/_resource.html.erb
<div id="education-<%= education.id %>">
  <div class="refreshable" data-refresh="<%= education_path(education, origin: origin_params) %>">
    <div class="text-center loading position-absolute pl-5 pt-2" \
         style="display: none">
      <div class="spinner-border" role="status">
        <span class="sr-only"><%= t("observatorio.loading") %></span>
      </div>
    </div>
    <div class="content">
      <%=
        render partial: "modal_form", locals: {
          url: edit_education_path(education),
          modal_id: "edit-education-#{education.id}-student",
          modal_title: Education.human_attribute_name(:student_edit)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: edit_education_path(education),
          modal_id: "edit-education-#{education.id}-school",
          modal_title: Education.human_attribute_name(:school_edit)
        }
      %>
      <%=
        render partial: "confirm_delete", locals: {
          record: education,
          confirm_message: Education.human_attribute_name(
            :student_destroy_confirm,
            school: tag.strong(display_name(education.school))
          ).html_safe,
          modal_id: "destroy-education-#{education.id}-student",
          modal_title: Education.human_attribute_name(:student_destroy)
        }
      %>
      <%=
        render partial: "confirm_delete", locals: {
          record: education,
          confirm_message: Education.human_attribute_name(
            :school_destroy_confirm,
            student: tag.strong(display_name(education.student))
          ).html_safe,
          modal_id: "destroy-education-#{education.id}-school",
          modal_title: Education.human_attribute_name(:school_destroy)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: new_link_path(link: {
            linkable_id: education.id,
            linkable_type: Education
          }),
          modal_id: "add-source-#{education.id}",
          modal_title: Education.human_attribute_name(:new_source)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: new_attachment_path(attachment: {
            attachable_id: education.id,
            attachable_type: Education
          }),
          modal_id: "add-attachment-#{education.id}",
          modal_title: Education.human_attribute_name(:new_attachment)
        }
      %>
      <% education.sources.each do |link| %>
        <%=
          render partial: "modal_form", locals: {
            url: edit_link_path(link),
            modal_id: "edit-link-#{link.id}",
            modal_title: Link.human_attribute_name(:edit)
          }
        %>
        <%=
          render partial: "confirm_delete", locals: {
            record: link,
            confirm_message: Link.human_attribute_name(
              :destroy_confirm, record: tag.strong(display_name(link))
            ).html_safe,
            modal_id: "destroy-link-#{link.id}",
            modal_title: Link.human_attribute_name(:destroy)
          }
        %>
      <% end %>
      <% education.attachments.each do |attachment| %>
        <%=
          render partial: "modal_form", locals: {
            url: edit_attachment_path(attachment),
            modal_id: "edit-attachment-#{attachment.id}",
            modal_title: Attachment.human_attribute_name(:edit)
          }
        %>
        <%=
          render partial: "confirm_delete", locals: {
            record: attachment,
            confirm_message: Attachment.human_attribute_name(
              :destroy_confirm, record: tag.strong(display_name(attachment))
            ).html_safe,
            modal_id: "destroy-attachment-#{attachment.id}",
            modal_title: Attachment.human_attribute_name(:destroy)
          }
        %>
      <% end %>
      <div class="media item">
        <div class="d-none d-md-inline mr-2 student-only">
          <%= image_tag education.school.picture&.thumb&.url || image_path("open-iconic/home.svg"),
                class:"rounded-circle thumb main" %>
        </div>
        <div class="d-none d-md-inline mr-2 school-only">
          <%= image_tag education.student.picture&.thumb&.url || image_path("open-iconic/person.svg"),
                class:"rounded-circle thumb main" %>
        </div>
        <div class="media-body mb-0 pb-2">
          <div class="d-inline-block">
            <span class="float-left mr-2">
              <strong class="mb-2 mb-md-0 student-only">
                <%= display_resource(education.school) %>
              </strong>
              <strong class="mb-2 mb-md-0 school-only">
                <%= display_resource(education.student) %>
              </strong>
            </span>
            <div class="d-none d-md-inline-block student-only">
              <% if can? :update, education %>
                <a href="#edit-education-<%= education.id %>-student"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:student_edit) %>">
                  <%= image_tag image_path("open-iconic/pencil.svg") %>
                </a>
              <% end %>
              <% if can? :delete, education %>
                <a href="#destroy-education-<%= education.id %>-student"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:student_destroy) %>">
                  <%= image_tag image_path("open-iconic/x.svg") %>
                </a>
              <% end %>
            </div>
            <div class="d-none d-md-inline-block school-only">
              <% if can? :update, education %>
                <a href="#edit-education-<%= education.id %>-school"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:school_edit) %>">
                  <%= image_tag image_path("open-iconic/pencil.svg") %>
                </a>
              <% end %>
              <% if can? :delete, education %>
                <a href="#destroy-education-<%= education.id %>-school"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:school_destroy) %>">
                  <%= image_tag image_path("open-iconic/x.svg") %>
                </a>
              <% end %>
            </div>
          </div>
          <% if education.degree %>
            <span class="small d-block">
              <strong><%= Education.human_attribute_name(:degree) %>:</strong>
              <%= display_resource(education.degree) %>
            </span>
          <% end %>
          <% if education.course %>
            <span class="small d-block">
              <strong><%= Education.human_attribute_name(:course) %>:</strong>
              <%= display_resource(education.course) %>
            </span>
          <% end %>
          <% if education.from_date %>
            <span class="small d-block">
              <strong><%= Education.human_attribute_name(:from_date) %>:</strong>
              <%= display_time(education.from_date) %>
              <% if education.approximate_dates %>
                <strong>*</strong>
              <% end %>
            </span>
          <% end %>
          <% if education.from_date || education.to_date %>
            <span class="small d-block">
              <strong><%= Education.human_attribute_name(:to_date) %>:</strong>
              <% if education.to_date %>
                <%= display_time(education.to_date) %>
                <% if education.approximate_dates %>
                  <strong>*</strong>
                <% end %>
              <% else %>
                -
              <% end %>
            </span>
          <% end %>
          <% if education.approximate_dates %>
            <strong class="small">* <%= Education.human_attribute_name(:approximate_dates_label) %></strong>
          <% end %>
          <span class="small d-block">
            <strong class="mr-1">
              <%= Education.human_attribute_name(:sources) %>:
            </strong>
            <div class="d-none d-md-inline-block">
              <% if can? :update, education %>
                <a href="#add-source-<%= education.id %>"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:new_source) %>">
                  <%= image_tag image_path("open-iconic/plus.svg") %>
                </a>
              <% end %>
            </div>
          </span>
          <% education.sources.each do |link| %>
            <div class="small d-block">
              <span class="float-left mr-2">
                <strong class="ml-3 mr-1 float-left">
                  <%= link_to(link.label, link_path(link, origin: origin_params)) %>
                </strong>
                <div class="small d-inline-block text-truncate float-left has-tooltip"
                     title="<%= link.url %>"
                     style="max-width: 150px; padding-top: 3px">
                  <%= link.url %>
                </div>
              </span>
              <div class="d-none d-md-inline-block">
                <% if can? :update, link %>
                  <a href="#edit-link-<%= link.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Link.human_attribute_name(:edit) %>">
                    <%= image_tag image_path("open-iconic/pencil.svg") %>
                  </a>
                <% end %>
                <% if can? :delete, link %>
                  <a href="#destroy-link-<%= link.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Link.human_attribute_name(:destroy) %>">
                    <%= image_tag image_path("open-iconic/x.svg") %>
                  </a>
                <% end %>
              </div>
            </div>
          <% end %>
          <span class="small d-block">
            <strong class="mr-1">
              <%= Education.human_attribute_name(:attachments) %>:
            </strong>
            <div class="d-none d-md-inline-block">
              <% if can? :update, education %>
                <a href="#add-attachment-<%= education.id %>"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= Education.human_attribute_name(:new_attachment) %>">
                  <%= image_tag image_path("open-iconic/plus.svg") %>
                </a>
              <% end %>
            </div>
          </span>
          <% education.attachments.each do |attachment| %>
            <div class="small d-block">
              <span class="mr-1">
                <strong class="ml-3">
                  <%= link_to attachment.label, attachment_path(attachment, origin: origin_params) %>
                </strong>
                <span><%= attachment.file_extension %></span>
                <span class="small">(<%= number_to_human_size(attachment.file_size) %>)</span>
              </span>
              <div class="d-none d-md-inline-block">
                <% if can? :update, attachment %>
                  <a href="#edit-attachment-<%= attachment.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Attachment.human_attribute_name(:edit) %>">
                    <%= image_tag image_path("open-iconic/pencil.svg") %>
                  </a>
                <% end %>
                <% if can? :delete, attachment %>
                  <a href="#destroy-attachment-<%= attachment.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Attachment.human_attribute_name(:destroy) %>">
                    <%= image_tag image_path("open-iconic/x.svg") %>
                  </a>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/educations/create.html.erb
<div class="modal-body student-only">
  <%= t("observatorio.models.education.student.created",
        school: tag.strong(display_name(@resource.school))).html_safe %>
</div>
<div class="modal-body school-only">
  <%= t("observatorio.models.education.school.created",
        student: tag.strong(display_name(@resource.student))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, refresh_element %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>

app/views/educations/destroy.html.erb
<div class="modal-body student-only">
  <%= t("observatorio.models.education.student.destroyed",
        school: tag.strong(display_name(@resource.school))).html_safe %>
</div>
<div class="modal-body school-only">
  <%= t("observatorio.models.education.school.destroyed",
        student: tag.strong(display_name(@resource.student))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, "#education-#{@resource.id}" %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>

app/views/educations/form.html.erb
<%= form_for @resource do |f| %>
  <div class="modal-body">
    <div class="form-group row school-only">
      <% student_id_error = @resource.errors[:student_id]&.first  %>
      <%= label_tag "education[student_id]",
            @resource.class.human_attribute_name(:student), class: "col-3" %>
      <%= select_tag "education[student_id]",
            options_for_select([nil] + people_options, @resource.student_id),
            class: "col-8 form-control form-control-sm #{"is-invalid" if student_id_error}",
            required: true, disabled: @resource.persisted? %>
      <% if student_id_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-3 offset-3">
              <%= student_id_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="form-group row student-only">
      <% school_id_error = @resource.errors[:school_id]&.first  %>
      <%= label_tag "education[school_id]",
            @resource.class.human_attribute_name(:school), class: "col-3" %>
      <%= select_tag "education[school_id]",
            options_for_select([nil] + schools_options, @resource.school_id),
            class: "col-8 form-control form-control-sm #{"is-invalid" if school_id_error}",
            required: true, disabled: @resource.persisted? %>
      <% if school_id_error %>
       <div class="invalid-feedback">
         <div class="row">
           <div class="col-3 offset-3">
             <%= school_id_error %>
           </div>
         </div>
       </div>
      <% end %>
    </div>
    <div class="form-group row">
      <% degree_id_error = @resource.errors[:degree]&.first %>
      <%= label_tag "education[degree_id]",
            @resource.class.human_attribute_name(:degree), class: "col-3" %>
      <%= select_tag "education[degree_id]",
            options_for_select([nil] + degrees_options, @resource.degree_id),
            class: "col-8 form-control form-control-sm #{"is-invalid" if degree_id_error}" %>
      <% if degree_id_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-8 offset-3">
              <%= degree_id_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="form-group row">
      <% course_id_error = @resource.errors[:course]&.first %>
      <%= label_tag "education[course_id]",
            @resource.class.human_attribute_name(:course), class: "col-3" %>
      <%= select_tag "education[course_id]",
            options_for_select([nil] + courses_options, @resource.course_id),
            class: "col-8 form-control form-control-sm #{"is-invalid" if course_id_error}" %>
      <% if course_id_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-3 offset-3">
              <%= course_id_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="form-group date-boundaries-group row">
      <% from_date_error = @resource.errors[:from_date]&.first %>
      <%= label_tag "education[from_date]",
            @resource.class.human_attribute_name(:from_date), class: "col-3" %>
      <%= date_field_tag "education[from_date]", @resource.from_date,
            class: "form-control form-control-sm col-8 #{"is-invalid" if from_date_error}" %>
      <% if from_date_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-3 offset-3">
              <%= from_date_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="form-group date-boundaries-group row">
      <% to_date_error = @resource.errors[:to_date]&.first %>
      <%= label_tag "education[to_date]",
            @resource.class.human_attribute_name(:to_date), class: "col-3" %>
      <%= date_field_tag "education[to_date]", @resource.to_date,
            class: "form-control form-control-sm col-8 #{"is-invalid" if to_date_error}" %>
      <% if to_date_error %>
        <div class="invalid-feedback">
          <div class="row">
            <div class="col-3 offset-3">
              <%= to_date_error %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <fieldset class="form-group">
      <div class="row">
        <%= label_tag "education[approximate_dates]",
              @resource.class.human_attribute_name(:approximate_dates), class: "col-3" %>
        <div class="form-control-sm form-control-check col-8">
          <div class="form-check">
            <input class="form-check-input"
                   type="radio"
                   name='education[approximate_dates]'
                   required
                   id="approximateDatesYes"
                   value="1"
                   <%= "checked" if @resource.approximate_dates %>>
            <label class="form-check-label" for="approximateDatesYes">
              <%= t("observatorio.true") %>
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input"
                   type="radio"
                   name='education[approximate_dates]'
                   required
                   id="approximateDatesNo"
                   value="0"
                   <%= "checked" unless @resource.approximate_dates %>>
            <label class="form-check-label" for="approximateDatesNo">
              <%= t("observatorio.false") %>
            </label>
          </div>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="modal-footer">
    <%= submit_tag t("observatorio.save"), class: "btn btn-primary btn-sm" %>
    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">
      <%= t("observatorio.cancel") %>
    </button>
  </div>
<% end %>

app/views/educations/index.html.erb
<div class="refreshable" data-refresh="<%= request.original_fullpath %>">
  <div class="pl-4 loading" style="display: none">
    <div class="spinner-border" role="status">
      <span class="sr-only"><%= t("observatorio.loading") %></span>
    </div>
  </div>
  <div class="content">
    <% @resources.each do |education| %>
      <%= render partial: "resource", locals: { education: education } %>
    <% end %>
  </div>
</div>

app/views/educations/show.html.erb
<%= render partial: "resource", locals: { education: @resource } %>

app/views/educations/update.html.erb
<div class="modal-body school-only">
  <%= t("observatorio.models.education.school.updated",
        student: tag.strong(display_name(@resource.student))).html_safe %>
</div>
<div class="modal-body student-only">
  <%= t("observatorio.models.education.student.updated",
        school: tag.strong(display_name(@resource.school))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, "#education-#{@resource.id}" %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>