config/routes.rb
Rails.application.routes.draw do
  # Errors
  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_server_error"
  # Devise
  devise_for :users, path: :account, path_names: { sign_in: "login", sign_out: "logout" }
  devise_scope(:user) { get "logout", to: "devise/sessions#destroy" }
  # Attachments
  resources :attachments do
    member do
      get :download, to: "attachments#download"
      get :history, to: "attachments#history"
    end
  end
  # Educations
  resources :educations
  # Education courses
  resources :education_courses do
    member do
      get :history, to: "education_courses#history"
    end
  end
  # Education degrees
  resources :education_degrees do
    member do
      get :history, to: "education_degrees#history"
    end
  end
  # Events
  resources :events do
    member do
      get   :description,        to: "events#description"
      get   :"description/edit", to: "events#edit_description"
      put   :description,        to: "events#update_description"
      patch :description,        to: "events#update_description"
      get   :history,            to: "events#history"
    end
  end
  resources :event_participants
  # Event Roles
  resources :event_roles do
    member do
      get :history, to: "event_roles#history"
    end
  end
  # Pictures
  resources :pictures
  # Imports
  namespace :imports, only: [:index, :show] do
    resources :memberships, only: [:create, :index, :show] do
      member do
        get :download, to: "memberships#download"
      end
    end
    resources :organizations, only: [:create, :index, :show] do
      member do
        get :download, to: "organizations#download"
      end
    end
  end
  # Links
  resources :links do
    member do
      get :download, to: "links#download"
      get :history, to: "links#history"
    end
  end
  # Locations
  resources :locations, only: [:show] do
    collection do
      post :reverse_geocode, to: "locations#reverse_geocode"
    end
  end
  # Names
  resources :names, except: [:show]
  # Notes
  resources :notes, except: [:edit, :update]
  # Organizations
  resources :organizations do
    member do
      get   :description,        to: "organizations#description"
      get   :"description/edit", to: "organizations#edit_description"
      put   :description,        to: "organizations#update_description"
      patch :description,        to: "organizations#update_description"
      get   :history,            to: "organizations#history"
    end
  end
  # Organization departments
  resources :organization_departments
  # Organiation members
  resources :organization_members
  # Organization owners
  resources :organization_owners
  # Organization positions
  resources :organization_positions do
    member do
      get :history, to: "organization_positions#history"
    end
  end
  # People
  resources :people do
    member do
      get   :biography,        to: "people#biography"
      get   :"biography/edit", to: "people#edit_biography"
      put   :biography,        to: "people#update_biography"
      patch :biography,        to: "people#update_biography"
      get   :history,          to: "people#history"
    end
  end
  # Preferences
  resource :preferences, only: [:edit, :update]
  # Relationships
  resources :relationships
  # Tags
  resources :tags do
    member do
      get :history, to: "tags#history"
    end
  end
  get "/event_tags/:id", to: redirect("/tags/%{id}"), as: "event_tag"
  get "/organization_tags/:id", to: redirect("/tags/%{id}"), as: "organization_tag"
  get "/person_tags/:id", to: redirect("/tags/%{id}"), as: "person_tag"
  # User Groups
  resources :user_groups, only: [:index, :show] do
    member do
      post "users", to: "user_groups#add_user", as: :add_user
      delete "users/:user_id", to: "user_groups#remove_user", as: :remove_user
    end
  end
  # Root
  root to: "home#index"
end

app/models/event_participant.rb
class EventParticipant < ApplicationRecord
  self.table_name = "events_participants"

  has_paper_trail
  has_location
  has_immutable_attributes :event_id, :participant_id, :participant_type
  has_date_boundaries from_date: :from_datetime, to_date: :to_datetime
  has_time_zone allow_nil: true
  has_links :sources
  has_attachments

  default_value :from_datetime, lambda { |o| o.event && o.event.started_at }
  default_value :to_datetime, lambda { |o| o.event && o.event.finished_at }
  default_value :approximate_dates, lambda { |o| o.event && o.event.approximate_dates }
  default_value :time_zone, lambda { |o| o.event && o.event.time_zone }

  belongs_to :event
  belongs_to :role, {
    class_name: "EventRole",
    inverse_of: :event_participants
  }
  belongs_to :participant, {
    inverse_of: :events_participant,
    polymorphic: true
  }

  validates_presence_of :event
  validates_presence_of :participant

  validate              :validate_duplicate

  def from_datetime_in_time_zone
    return nil if from_datetime.nil? || time_zone.nil?
    from_datetime.in_time_zone(time_zone)
  end

  def to_datetime_in_time_zone
    return nil if to_datetime.nil? || time_zone.nil?
    to_datetime.in_time_zone(time_zone)
  end

  private

  def validate_duplicate
    return unless event.present? && participant.present?
    return if self.class
                  .where(":id IS NULL OR id != :id", id: id)
                  .where(event: event)
                  .where(participant: participant)
                  .where(role: role)
                  .where(location: location)
                  .where("from_datetime <= :to_datetime OR " \
                         ":to_datetime IS NULL OR " \
                         "from_datetime IS NULL",
                         to_datetime: to_datetime)
                  .where("to_datetime >= :from_datetime OR " \
                         ":from_datetime IS NULL OR " \
                         "to_datetime IS NULL",
                         from_datetime: from_datetime)
                  .empty?
    errors.add(:event_id, I18n.t("errors.messages.taken"))
    errors.add(:participant_id, I18n.t("errors.messages.taken"))
  end
end

app/controllers/event_participants_controller.rb
class EventParticipantsController < ResourcesController
  layout false

  # GET /event_participants
  def index
    super
    @resources = @resources
                   .includes(:event,
                             :role,
                             :location,
                             :sources,
                             :attachments)
                   .order("events.name")
  end

  private

  def authorize!(action, resource)
    if action == :list && resource == EventParticipant
      participant_id = params.require(:event_participant)[:participant_id]
      if participant_id.present?
        participant_klass = params.require(:event_participant)
                                  .require(:participant_type)
                                  .constantize
        participant = participant_klass.find(participant_id)
        authorize! :read, participant
      else
        event_id = params.require(:event_participant)
                         .require(:event_id)
        event = Event.find(event_id)
        authorize! :read, event
      end
    else
      super
    end
  end

  def resources_per_page
    nil
  end

  def resources_class
    EventParticipant
  end

  def index_params
    index_or_new_params
  end

  def new_params
    index_or_new_params
  end

  def create_params
    params.require(:event_participant)
          .permit(:event_id,
                  :participant_id,
                  :participant_type,
                  :role_id,
                  :from_datetime,
                  :to_datetime,
                  :approximate_dates,
                  :location_id)
  end

  def update_params
    params.require(:event_participant)
          .permit(:role_id,
                  :from_datetime,
                  :to_datetime,
                  :approximate_dates,
                  :location_id)
  end

  def index_or_new_params
    params.require(:event_participant)
          .permit(:event_id,
                  :participant_id,
                  :participant_type)
  end
end

app/helpers/event_participants_helper.rb
module EventParticipantsHelper
  def participants_options
    names_sorted = Name.where(main: true)
                       .where(nameable_type: [Person.name, Organization.name])
                       .order(:value)
    names_sorted.map do |name|
      [name.value, name.nameable_id, :"data-type" => name.nameable_type]
    end
  end

  def roles_options
    @_roles_options ||= begin
      EventRole.all.map { |o| [display_name(o), o.id] }.sort_by(&:first)
    end
  end

  def events_options
    Event.all.map do |o|
      [display_name(o), o.id, {
        :"data-location-id" => o.location_id,
        :"data-location-address" => truncated_address(o.location),
        :"data-started-at" => o.started_at && o.started_at.strftime("%Y-%m-%d %H:%M"),
        :"data-finished-at" => o.finished_at && o.finished_at.strftime("%Y-%m-%d %H:%M"),
        :"data-time-zone" => o.time_zone
      }]
    end
  end
end

app/views/event_participants/_history_entry.html.erb
<% item = version.item_state(belongs_to: true) %>
<% participant = item.participant %>
<% version_event = version.event %>
<div class="media item">
  <div class="media-body mb-0 mt-0 mb-2">
    <div class="d-inline-block main">
      <strong class="mb-md-0">
        <%= display_time(version.created_at) %>
      </strong>
      &middot;
      <%= display_user(version.user) %>
    </div>
    <span class="ml-2 d-block">
      <span class="event-only">
        <%= t("paper_trail.event_participant.event.#{version_event}",
              participant: tag.strong(display_resource(participant))).html_safe %>
      </span>
      <span class="participant-only">
        <%= t("paper_trail.event_participant.participant.#{version_event}",
              event: tag.strong(display_resource(item.event))).html_safe %>
      </span>
      <% if version_event != "destroy" %>
        <a class="btn btn-info small btn-sm py-0 px-1 ml-1"
           data-toggle="collapse"
           href="#details<%= version.id %>"
           role="button"
           aria-expanded="false"
           aria-controls="details">
          <%= t("paper_trail.details") %>
        </a>
      <% end %>
    </span>
    <% if version_event != "destroy" %>
      <div class="collapse small" id="details<%= version.id %>">
        <ul class="mt-1 mb-0 pl-4" style="list-style-type: none">
          <% if version.converted_changeset.key?("role_id") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:role) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["role_id"].reverse.map { |c| display_resource(c) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("from_datetime") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:from_datetime) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["from_datetime"].reverse.map { |d|
                      display_time(d, time_zone: item.time_zone)
                    }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("to_datetime") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:to_datetime) %>:</strong>
              <% time_zone = version.converted_changeset.key?("time_zone") ?
                version.converted_changeset["time_zone"].last : item.time_zone %>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["to_datetime"].reverse.map { |d|
                      display_time(d, time_zone: item.time_zone)
                    }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("time_zone") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:time_zone) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["time_zone"].reverse
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("approximate_dates") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:approximate_dates) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["approximate_dates"].reverse.map { |b| display_boolean(b) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
          <% if version.converted_changeset.key?("location_id") %>
            <li>
              <strong><%= EventParticipant.human_attribute_name(:location) %>:</strong>
              <%= Differ.diff_by_line(
                    *version.converted_changeset["location_id"].reverse.map { |b| display_name(b) }
                  ).format_as(:html).html_safe %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/event_participants/_resource.html.erb
<div id="event_participant-<%= event_participant.id %>">
  <div class="refreshable"
       data-refresh="<%= event_participant_path(event_participant, origin: origin_params) %>">
    <div class="text-center loading position-absolute pl-5 pt-2" \
         style="display: none">
      <div class="spinner-border" role="status">
        <span class="sr-only"><%= t("observatorio.loading") %></span>
      </div>
    </div>
    <div class="content">
      <%=
        render partial: "modal_form", locals: {
          url: edit_event_participant_path(event_participant),
          modal_id: "edit-event-participant-#{event_participant.id}-participant",
          modal_title: EventParticipant.human_attribute_name(:participant_edit)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: edit_event_participant_path(event_participant),
          modal_id: "edit-event-participant-#{event_participant.id}-event",
          modal_title: EventParticipant.human_attribute_name(:event_edit)
        }
      %>
      <%=
        render partial: "confirm_delete", locals: {
          record: event_participant,
          confirm_message: EventParticipant.human_attribute_name(
            :participant_destroy_confirm,
            event: tag.strong(display_name(event_participant.event))
          ).html_safe,
          modal_id: "destroy-event-participant-#{event_participant.id}-participant",
          modal_title: EventParticipant.human_attribute_name(:participant_destroy)
        }
      %>
      <%=
        render partial: "confirm_delete", locals: {
          record: event_participant,
          confirm_message: EventParticipant.human_attribute_name(
            :event_destroy_confirm,
            participant: tag.strong(display_name(event_participant.participant))
          ).html_safe,
          modal_id: "destroy-event-participant-#{event_participant.id}-event",
          modal_title: EventParticipant.human_attribute_name(:event_destroy)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: new_link_path(link: {
            linkable_id: event_participant.id, linkable_type: EventParticipant
          }),
          modal_id: "add-source-#{event_participant.id}",
          modal_title: EventParticipant.human_attribute_name(:new_source)
        }
      %>
      <%=
        render partial: "modal_form", locals: {
          url: new_attachment_path(attachment: {
            attachable_id: event_participant.id, attachable_type: EventParticipant
          }),
          modal_id: "add-attachment-#{event_participant.id}",
          modal_title: EventParticipant.human_attribute_name(:new_attachment)
        }
      %>
      <% event_participant.sources.each do |link| %>
        <%=
          render partial: "modal_form", locals: {
            url: edit_link_path(link),
            modal_id: "edit-link-#{link.id}",
            modal_title: Link.human_attribute_name(:edit)
          }
        %>
        <%=
          render partial: "confirm_delete", locals: {
            record: link,
            confirm_message: Link.human_attribute_name(
              :destroy_confirm, record: tag.strong(display_name(link))
            ).html_safe,
            modal_id: "destroy-link-#{link.id}",
            modal_title: Link.human_attribute_name(:destroy)
          }
        %>
      <% end %>
      <% event_participant.attachments.each do |attachment| %>
        <%=
          render partial: "modal_form", locals: {
            url: edit_attachment_path(attachment),
            modal_id: "edit-attachment-#{attachment.id}",
            modal_title: Attachment.human_attribute_name(:edit)
          }
        %>
        <%=
          render partial: "confirm_delete", locals: {
            record: attachment,
            confirm_message: Attachment.human_attribute_name(
              :destroy_confirm, record: tag.strong(display_name(attachment))
            ).html_safe,
            modal_id: "destroy-attachment-#{attachment.id}",
            modal_title: Attachment.human_attribute_name(:destroy)
          }
        %>
      <% end %>
      <% if event_participant.location %>
        <%=
          render partial: "modal_map", locals: {
            modal_id: "location-#{event_participant.id}-modal",
            data_location_path: location_path(event_participant.location_id)
          }
        %>
      <% end %>
      <div class="media item">
        <div class="d-none d-md-inline mr-2 event-only">
          <% fallback_image = event_participant.participant.is_a?(Person) ?
              "open-iconic/person.svg" : "open-iconic/home.svg" %>
          <%= image_tag event_participant.participant.picture&.thumb&.url || image_path(fallback_image),
                class:"rounded-circle thumb main" %>
        </div>
        <div class="media-body mb-0 pb-2">
          <div class="d-inline-block">
            <span class="float-left mr-2">
              <strong class="mb-2 mb-md-0 participant-only">
                <%= display_resource(event_participant.event) %>
              </strong>
              <strong class="mb-2 mb-md-0 event-only">
                <%= display_resource(event_participant.participant) %>
              </strong>
            </span>
            <div class="d-none d-md-inline-block participant-only">
              <% if can? :update, event_participant %>
                <a href="#edit-event-participant-<%= event_participant.id %>-participant"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:participant_edit) %>">
                  <%= image_tag image_path("open-iconic/pencil.svg") %>
                </a>
              <% end %>
              <% if can? :delete, event_participant %>
                <a href="#destroy-event-participant-<%= event_participant.id %>-participant"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:participant_destroy) %>">
                  <%= image_tag image_path("open-iconic/x.svg") %>
                </a>
              <% end %>
            </div>
            <div class="d-none d-md-inline-block event-only">
              <% if can? :update, event_participant %>
                <a href="#edit-event-participant-<%= event_participant.id %>-event"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:event_edit) %>">
                  <%= image_tag image_path("open-iconic/pencil.svg") %>
                </a>
              <% end %>
              <% if can? :delete, event_participant %>
                <a href="#destroy-event-participant-<%= event_participant.id %>-event"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:event_destroy) %>">
                  <%= image_tag image_path("open-iconic/x.svg") %>
                </a>
              <% end %>
            </div>
          </div>
          <% if event_participant.role %>
            <span class="small d-block">
              <strong><%= EventParticipant.human_attribute_name(:role) %>:</strong>
              <%= display_resource(event_participant.role) %>
            </span>
          <% end %>
          <% if event_participant.from_datetime %>
            <span class="small d-block">
              <strong><%= EventParticipant.human_attribute_name(:from_datetime) %>:</strong>
              <%= display_time(event_participant.from_datetime) %>
              <% if event_participant.approximate_dates %>
                <strong>*</strong>
              <% end %>
            </span>
          <% end %>
          <% if event_participant.from_datetime || event_participant.to_datetime %>
            <span class="small d-block">
              <strong><%= EventParticipant.human_attribute_name(:to_datetime) %>:</strong>
              <% if event_participant.to_datetime %>
                <%= display_time(event_participant.to_datetime) %>
                <% if event_participant.approximate_dates %>
                  <strong>*</strong>
                <% end %>
              <% else %>
                -
              <% end %>
            </span>
          <% end %>
          <% if event_participant.approximate_dates %>
            <strong class="small">* <%= EventParticipant.human_attribute_name(:approximate_dates_label) %></strong>
          <% end %>
          <% if event_participant.time_zone %>
          <span class="small d-block">
            <strong><%= EventParticipant.human_attribute_name(:time_zone) %>:</strong>
            <%= event_participant.time_zone %>
          </span>
          <% end %>
          <% if event_participant.location %>
            <span class="small d-block">
              <strong><%= EventParticipant.human_attribute_name(:location) %>:</strong>
              <a href="#location-<%= event_participant.id %>-modal" data-toggle="modal">
                <%= display_name(event_participant.location)%>
              </a>
            </span>
          <% end %>
          <span class="small d-block">
            <strong class="mr-1">
              <%= EventParticipant.human_attribute_name(:sources) %>:
            </strong>
            <div class="d-none d-md-inline-block">
              <% if can? :update, event_participant %>
                <a href="#add-source-<%= event_participant.id %>"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:new_source) %>">
                  <%= image_tag image_path("open-iconic/plus.svg") %>
                </a>
              <% end %>
            </div>
          </span>
          <% event_participant.sources.each do |link| %>
            <div class="small d-block">
              <span class="float-left mr-2">
                <strong class="ml-3 mr-1 float-left">
                  <%= link_to(link.label, link_path(link, origin: origin_params)) %>
                </strong>
                <div class="small d-inline-block text-truncate float-left has-tooltip"
                     title="<%= link.url %>"
                     style="max-width: 150px; padding-top: 3px">
                  <%= link.url %>
                </div>
              </span>
              <div class="d-none d-md-inline-block">
                <% if can? :update, link %>
                  <a href="#edit-link-<%= link.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Link.human_attribute_name(:edit) %>">
                    <%= image_tag image_path("open-iconic/pencil.svg") %>
                  </a>
                <% end %>
                <% if can? :delete, link %>
                  <a href="#destroy-link-<%= link.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Link.human_attribute_name(:destroy) %>">
                    <%= image_tag image_path("open-iconic/x.svg") %>
                  </a>
                <% end %>
              </div>
            </div>
          <% end %>
          <span class="small d-block">
            <strong class="mr-1">
              <%= EventParticipant.human_attribute_name(:attachments) %>:
            </strong>
            <div class="d-none d-md-inline-block">
              <% if can? :update, event_participant %>
                <a href="#add-attachment-<%= event_participant.id %>"
                   class="action has-tooltip"
                   data-toggle="modal"
                   data-placement="top"
                   title="<%= EventParticipant.human_attribute_name(:new_attachment) %>">
                  <%= image_tag image_path("open-iconic/plus.svg") %>
                </a>
              <% end %>
            </div>
          </span>
          <% event_participant.attachments.each do |attachment| %>
            <div class="small d-block">
              <span class="mr-1">
                <strong class="ml-3">
                  <%= link_to attachment.label, attachment_path(attachment, origin: origin_params) %>
                </strong>
                <span><%= attachment.file_extension %></span>
                <span class="small">(<%= number_to_human_size(attachment.file_size) %>)</span>
              </span>
              <div class="d-none d-md-inline-block">
                <% if can? :update, attachment %>
                  <a href="#edit-attachment-<%= attachment.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Attachment.human_attribute_name(:edit) %>">
                    <%= image_tag image_path("open-iconic/pencil.svg") %>
                  </a>
                <% end %>
                <% if can? :delete, attachment %>
                  <a href="#destroy-attachment-<%= attachment.id %>"
                     class="action has-tooltip"
                     data-toggle="modal"
                     data-placement="top"
                     title="<%= Attachment.human_attribute_name(:destroy) %>">
                    <%= image_tag image_path("open-iconic/x.svg") %>
                  </a>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/event_participants/create.html.erb
<div class="modal-body participant-only">
  <%= t("observatorio.models.event_participant.participant.created",
        event: tag.strong(display_name(@resource.event))).html_safe %>
</div>
<div class="modal-body event-only">
  <%= t("observatorio.models.event_participant.event.created",
        participant: tag.strong(display_name(@resource.participant))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, refresh_element %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>

app/views/event_participants/destroy.html.erb
<div class="modal-body participant-only">
  <%= t("observatorio.models.event_participant.participant.destroyed",
        event: tag.strong(display_name(@resource.event))).html_safe %>
</div>
<div class="modal-body event-only">
  <%= t("observatorio.models.event_participant.event.destroyed",
        participant: tag.strong(display_name(@resource.participant))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, "#event_participant-#{@resource.id}" %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>

app/views/event_participants/index.html.erb
<div class="refreshable" data-refresh="<%= request.original_fullpath %>">
  <div class="pl-4 loading" style="display: none">
    <div class="spinner-border" role="status">
      <span class="sr-only"><%= t("observatorio.loading") %></span>
    </div>
  </div>
  <div class="content">
    <% @resources.each do |event_participant| %>
      <%= render partial: "resource", locals: { event_participant: event_participant } %>
    <% end %>
  </div>
</div>

app/views/event_participants/show.html.erb
<%= render partial: "resource", locals: { event_participant: @resource } %>

app/views/event_participants/update.html.erb
<div class="modal-body participant-only">
  <%= t("observatorio.models.event_participant.participant.updated",
        event: tag.strong(display_name(@resource.event))).html_safe %>
</div>
<div class="modal-body event-only">
  <%= t("observatorio.models.event_participant.event.updated",
        participant: tag.strong(display_name(@resource.participant))).html_safe %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">
    <%= t("observatorio.dialog.ok") %>
  </button>
</div>

<%= hidden_field_tag :refresh_element, "#event_participant-#{@resource.id}" %>
<%= hidden_field_tag :refresh_element, "#history-subsection" %>